### ISSUE TITLE
noise_gate.pro wrong contents?

### ISSUE THREAD

**Issue by D-DePablos** [Richardjmorton/noise_gating#1]
Hi, unsure if this is the encoding or what, but the noise_gate.pro file shows:
bookmark88(�SK�~m�A�TApplicationsexelisidl85libroutinestime_seriesnoise_gate.pro$4DP`t%;������N�1P�������A��`|#��	file:///Macintosh HD�`ntA���$5EA677FE-D62E-34FA-B871-EA435A6542EC���/3dnibpro????������ T@D  | � � � �  �0 t�t��t"�

When opened on VS code.

Maybe a MAC vs Linux thing?

**Comment by Richardjmorton** [comment]
Yep, my bad. For some reason I had created an alias to the files in my desktop repository. All sorted now.
